version: "3.3"

services:
  rawAirbnbDB:
    image: mysql
    container_name: rawAirbnbDB
    restart: always
    environment:
      MYSQL_DATABASE: 'rawAirbnbDB'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - 3307:3306
    volumes:
      - type: bind
        source: ./database
        target: /opt/database/rawAirbnbDB

  AirbnbDB:
    image: mysql
    container_name: AirbnbDB
    restart: always
    environment:
      MYSQL_DATABASE: 'AirbnbDB'
      MYSQL_ROOT_PASSWORD: 'admin'  # SuperUser
    ports:
      - 3308:3306
    volumes:
      - type: bind
        source: ./database
        target: /opt/database/AirbnbDB
